<?xml version="1.0" encoding="utf-8"?><Database Name="SV" Class="SVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-AD054TF\SQLEXPRESS;Initial Catalog=SV;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="QLSV.Properties.Settings" SettingsPropertyName="SVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SinhVien" Member="SinhViens">
    <Type Name="SinhVien">
      <Column Name="MaSV" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenSV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Diem" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MaMH" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>